# -*- coding: utf-8 -*-
"""ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZMaTDX3Pnp9f9katcc8vQj20u2N3iZYz
"""

#import the pandas model and represent by object pd
import pandas as pd

"""dataset=pd.read_csv("/content/salary dataset.csv")"""

#read the dataser
dataset=pd.read_csv("/content/salary dataset.csv")

dataset

#input x and output is salary
x=dataset[["Experience (Years)"]]
y=dataset[["Salary (₹)"]]

#split the dataset and train model
from sklearn.model_selection import train_test_split

#split the dataset
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=42)

#import the linearRegression
from sklearn.linear_model import LinearRegression

#train the linear Regression model
reg=LinearRegression()

#fit is used to train the model
reg.fit(x_train,y_train)

#predict and evaluate
y_pred=reg.predict(x_test)
y_pred

#save model using pickle
import pickle
filename="LinearRegression_salary.sav"
pickle.dump(reg,open(filename,"wb"))

#loaded the model
loaded_model=pickle.load(open(filename,"rb"))

#result
result=loaded_model.predict([[20]])
print(result)

#check model accuracy so we used r2 score
from sklearn.metrics import r2_score
r2=r2_score(y_test,y_pred)
print("r2 score",r2)

from google.colab import drive
drive.mount('/content/drive')